spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        - id: user-service
          uri: lb://auth-service
          predicates:
            - Path=/users/**
          filters:
            - AuthenticationFilter

        - id: orders-api
          uri: lb://orders-api
          predicates:
            - Path=/internal/api/v1/orders/**
          filters:
            - AuthenticationFilter

        - id: products-api
          uri: lb://products-api
          predicates:
            - Path=/internal/api/v1/products/**
          filters:
            - AuthenticationFilter

        - id: clients-api
          uri: lb://clients-api
          predicates:
            - Path=/internal/api/v1/customers/**
          filters:
            - AuthenticationFilter

        - id: eureka-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/main
          filters:
            - RewritePath=/eureka/(?<segment>.*), /$\{segment}
        - id: eureka-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**

jwt:
  secret: ${jwt_token}